import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * The knowledge base sidebar is generated automatically from the folder tree
 * under docs/. Each section folder carries a `_category_.json` that controls
 * its label and position, so adding an article is a matter of creating one
 * Markdown file — no manual sidebar edit is required. This keeps navigation and
 * content in sync by construction, which the docs-impact and coverage checks
 * then verify.
 */
const sidebars: SidebarsConfig = {
  knowledgeBase: [
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
};

export default sidebars;
